In [3]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import log_loss

In [4]:
file_path = r"C:\Users\dipak\OneDrive\desktop\github_ai\ml_with_python\two_module\logistic_regression\ChurnData.csv"

In [5]:
df = pd.read_csv(file_path)

In [6]:
df.sample(5)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
166    70.0  36.0      8.0    50.0  1.0    15.0    0.0       1.0       0.0   
48     71.0  56.0     23.0   170.0  1.0    30.0    0.0       1.0       0.0   
172     9.0  40.0     13.0    38.0  4.0     7.0    1.0       1.0       1.0   
13     69.0  51.0     11.0   438.0  4.0    23.0    1.0       1.0       0.0   
184    26.0  55.0     13.0    61.0  1.0    26.0    0.0       1.0       0.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
166    20.55  ...    0.0       0.0       0.0     0.0    0.0    3.023    3.240   
48     14.20  ...    1.0       0.0       1.0     1.0    0.0    2.653    3.296   
172     3.35  ...    1.0       1.0       1.0     1.0    1.0    1.209    3.045   
13     29.00  ...    1.0       1.0       0.0     1.0    0.0    3.367    3.240   
184     4.25  ...    0.0       0.0       1.0     1.0    0.0    1.447    3.367   

     lninc  custcat  churn  
166  3.912      2.0    0.0  
48   5.136      4.0    0.0  
172  3.638      4.0    1.0  
13   6.082      4.0    0.0  
184  4.111      3.0    0.0  

[5 rows x 28 columns]

In [7]:
df.columns

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

In [9]:
churn_df = df[["tenure","age","address","income","ed","employ","equip","churn"]]

In [10]:
churn_df["churn"] = churn_df["churn"].astype('int')
churn_df

C:\Users\dipak\AppData\Local\Temp\ipykernel_4756\3277996479.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  churn_df["churn"] = churn_df["churn"].astype('int')


tenure   age  address  income   ed  employ  equip  churn
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0      1
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0      1
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0      0
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0      0
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0      0
..      ...   ...      ...     ...  ...     ...    ...    ...
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0      0
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0      0
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0      0
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0      1
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0      0

[200 rows x 8 columns]

In [13]:
X = np.asarray(churn_df[["tenure","age","address","income","ed","employ","equip"]])
y = np.asarray(churn_df[["churn"]])
print(X[0:5])
print(y[0:5])

[[ 11.  33.   7. 136.   5.   5.   0.]
 [ 33.  33.  12.  33.   2.   0.   0.]
 [ 23.  30.   9.  30.   1.   2.   0.]
 [ 38.  35.   5.  76.   2.  10.   1.]
 [  7.  35.  14.  80.   2.  15.   0.]]
[[1]
 [1]
 [0]
 [0]
 [0]]
